// Code generated by protoc-gen-gogo.
// source: google/protobuf/any.proto
// DO NOT EDIT!

/*
Package graphql is a generated protocol buffer package.

It is generated from these files:
	google/protobuf/any.proto
	google/protobuf/empty.proto
	google/protobuf/timestamp.proto

It has these top-level messages:
	Any
	Empty
	Timestamp
*/
package graphql

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
