// Code generated by protoc-gen-gogo.
// source: google/protobuf/timestamp.proto
// DO NOT EDIT!

package graphql

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
