// Code generated by protoc-gen-gogo.
// source: gogogql.proto
// DO NOT EDIT!

/*
Package gogogqlproto is a generated protocol buffer package.

It is generated from these files:
	gogogql.proto

It has these top-level messages:
*/
package gogogqlproto

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var E_GraphqlMessage = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         64040,
	Name:          "gogogqlproto.graphql_message",
	Tag:           "bytes,64040,opt,name=graphql_message",
}

var E_GraphqlField = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65040,
	Name:          "gogogqlproto.graphql_field",
	Tag:           "bytes,65040,opt,name=graphql_field",
}

func init() {
	proto.RegisterExtension(E_GraphqlMessage)
	proto.RegisterExtension(E_GraphqlField)
}
