// Code generated by protoc-gen-gogo.
// source: gogogql.proto
// DO NOT EDIT!

/*
Package gogogqlproto is a generated protocol buffer package.

It is generated from these files:
	gogogql.proto

It has these top-level messages:
*/
package gogogqlproto

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var E_Graphql = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64040,
	Name:          "gogogqlproto.graphql",
	Tag:           "varint,64040,opt,name=graphql",
}

func init() {
	proto.RegisterExtension(E_Graphql)
}
